# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    libjack-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml setup.py .
COPY daisys_mcp/ ./daisys_mcp/

# Install package
RUN pip install --no-cache-dir .

ENV PYTHONUNBUFFERED=1

# Entrypoint for MCP server
ENTRYPOINT ["daisys-mcp"]
